# Generated by Django 3.2.3 on 2024-02-20 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_usersubscribe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscribe',
            options={'ordering': ['-pub_date']},
        ),
    ]
