# Generated by Django 3.2.3 on 2024-02-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240220_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.DeleteModel(
            name='UserSubscribe',
        ),
    ]
