# Generated by Django 3.2.3 on 2024-02-27 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^(?!me$)[\\ \\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
